name: CI Workflow Execution

on: [push, pull_request]

jobs:
  lint:
    - name: Check out repository
      uses: actions/checkout@v3
    uses: ./lint.yml
  tests:
    needs: lint
    - name: Check out repository
      uses: actions/checkout@v3
    uses: ./tests.yml
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: tests
    - name: Check out repository
      uses: actions/checkout@v3
    uses: ./deploy.yml
