name: CI Workflow Execution

on: [push, pull_request]

jobs:
  lint:
    uses: actions/checkout@v2
    uses: ./.github/workflows/lint.yml
  tests:
    needs: lint
    uses: actions/checkout@v2
    uses: ./.github/workflows/tests.yml
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: tests
    uses: actions/checkout@v2
    uses: ./.github/workflows/deploy.yml
